spring:
  #配置数据库远程连接
  datasource:
    url: jdbc:mysql://139.199.66.139:3306/photoview?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

  jpa:
    properties:
      hibernate:
        hbm2dd1:
          auto: true
        ddl-auto: updata
        enable_lazy_load_no_trans: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
